# Generated by Django 5.1 on 2024-08-29 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Загаловок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('completed', models.BooleanField(default=True, verbose_name='Завершена')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Избранная')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('priority', models.IntegerField(choices=[(1, 'Низкий'), (2, 'Ниже среднего'), (3, 'Средний'), (4, 'Выше среднего'), (5, 'Высокий')], null=True, verbose_name='Приорететность')),
                ('slug', models.SlugField(max_length=150, null=True, unique=True, verbose_name='URL')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['id', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_favorite', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('favorites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites_task', to='tasks.tasks')),
            ],
            options={
                'verbose_name': 'избранная',
                'verbose_name_plural': 'Избранные',
            },
        ),
    ]
